- frontend/src/App.css
- frontend/src/pages/IDEPage/components/editor/index.jsx
- frontend/src/pages/IDEPage/components/header/components/Button.jsx
- frontend/src/pages/IDEPage/components/header/components/ExeButton.jsx
- frontend/src/pages/IDEPage/components/header/components/ProfileBadge.jsx
- frontend/src/pages/IDEPage/components/header/index.jsx
> 21 idepage header UI 구현

- backend/src/main/java/com/nakaligoba/backend/controller/FileController.java
- backend/src/main/java/com/nakaligoba/backend/domain/BaseEntity.java
- backend/src/main/java/com/nakaligoba/backend/entitiy/FileEntity.java
- backend/src/main/java/com/nakaligoba/backend/repository/FileRepository.java
- backend/src/main/java/com/nakaligoba/backend/service/FileService.java
- createdAt과 updatedAt의 BaseEntity 작성
- 코드 실행 API 작성
- 코드 파일 저장 / 수정 / 불러오기 기능을 구현
> [feat] BaseEntity적용 및 코드 실행 API 작성과 코드 저장,불러오기 기능 구현

- backend/src/main/java/com/nakaligoba/backend/controller/FileController.java
`import NotEmpty` -> `import NotBlank`
버그 #36 
Closes #37
> [fix] 37 filecontroller import 문제

- backend/src/main/java/com/nakaligoba/backend/entity/BaseEntity.java
- backend/src/main/java/com/nakaligoba/backend/entity/FileEntity.java
- backend/src/main/java/com/nakaligoba/backend/repository/FileRepository.java
- backend/src/main/java/com/nakaligoba/backend/service/FileService.java
> [fix] 39 네이밍 이슈

- frontend/src/pages/IDEPage/components/chatroom/index.jsx
- frontend/src/pages/IDEPage/index.jsx
> feat: idepage chatroom UI 구현

- backend/src/main/java/com/nakaligoba/backend/filter/CorsFilter.java
> feat: cors 필터 적용

- frontend/package-lock.json
- frontend/package.json
- frontend/src/pages/IDEPage/components/console/components/CloseButton.jsx
- frontend/src/pages/IDEPage/components/console/components/Tab.jsx
- frontend/src/pages/IDEPage/components/console/index.css
- frontend/src/pages/IDEPage/components/console/index.jsx
- frontend/src/pages/IDEPage/components/editor/components/CloseButton.jsx
- frontend/src/pages/IDEPage/components/editor/components/Tab.jsx
- frontend/src/pages/IDEPage/components/editor/index.css
- frontend/src/pages/IDEPage/components/editor/index.jsx
- frontend/src/pages/IDEPage/index.jsx
> [design] idepage console,editor UI 구현

- backend/build.gradle
- backend/src/main/java/com/nakaligoba/backend/config/DockerConfig.java
- backend/src/main/java/com/nakaligoba/backend/controller/FileController.java
- backend/src/main/java/com/nakaligoba/backend/domain/Language.java
- backend/src/main/java/com/nakaligoba/backend/entity/FileEntity.java
- backend/src/main/java/com/nakaligoba/backend/service/DockerTemplate.java
- backend/src/main/java/com/nakaligoba/backend/service/RunFileService.java
- backend/src/test/java/com/nakaligoba/backend/service/RunFileServiceTest.java
- 코드 실행 요청에 따른 컨테이너 생성, 코드 실행, 컨텡이너 삭제
Closes #11
> [feat] 코드 컴파일 및 빌드 후 실행

- backend/Dockerfile
> [chore] was 도커 파일 작성

- backend/src/main/java/com/nakaligoba/backend/entity/ChatMessage.java
- backend/src/main/java/com/nakaligoba/backend/entity/MemberEntity.java
- backend/src/main/java/com/nakaligoba/backend/entity/MemberProjectEntity.java
- backend/src/main/java/com/nakaligoba/backend/entity/ProjectEntity.java
- backend/src/main/java/com/nakaligoba/backend/entity/Role.java
- backend/src/main/resources/db/schema.sql
- [] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [] 💯 테스트는 잘 통과했나요?
- [] 🏗️ 빌드는 성공했나요?
- [] 🧹 불필요한 코드는 제거했나요?
- [] 💭 이슈는 등록했나요?
- [] 🏷️ 라벨은 등록했나요?
- [] 💻 git rebase를 사용했나요?
> 60 memberentity 및 sql 수정

- frontend/src/pages/IDEPage/components/sidebar/index.jsx
> css, tabHandleClick 코드 일부수정

- frontend/package-lock.json
- frontend/package.json
- frontend/src/pages/IDEPage/components/file_explorer/Contextmenu.css
- frontend/src/pages/IDEPage/components/file_explorer/Contextmenu.jsx
- frontend/src/pages/IDEPage/components/file_explorer/FileSearch.jsx
- frontend/src/pages/IDEPage/components/file_explorer/Form.jsx
- frontend/src/pages/IDEPage/components/file_explorer/TabSettings.jsx
- frontend/src/pages/IDEPage/components/file_explorer/index.css
- frontend/src/pages/IDEPage/components/file_explorer/index.jsx
파일 및 폴더 생성, 수정, 삭제 기능 
컨텍스트 메뉴 구현 
생성, 수정, 삭제시 트리구조 반영
settings 탭 ui 구현 
css 수정 및 추가 
> 24 idepage filedirectory UI 구현

- frontend/src/assets/view-list.svg
- frontend/src/pages/IDEPage/components/header/components/ProjectTitleButton.jsx
- frontend/src/pages/IDEPage/components/header/index.jsx
> add: project list modal open button

- backend/src/main/java/com/nakaligoba/backend/controller/ProjectController.java
- backend/src/main/java/com/nakaligoba/backend/entity/ProjectEntity.java
- backend/src/main/java/com/nakaligoba/backend/repository/ProjectRepository.java
- backend/src/main/java/com/nakaligoba/backend/service/ProjectService.java
프로젝트 파일 생성 및 목록 API를 작성하였습니다.
서비스 레이어에 request 또는 response DTO 객체들을 
필요할때마다 만들었는데
이 부분에 대해서 개선되어야 할 부분이 있다면 알려주시면 감사하겠습니다!👍
프로젝트 파일을 생성할 때 template을 추가하는 것을 고민하다가 잊고 PR을 올렸습니다..
이게 DB에 저장하려면 Entity에 template 필드를 추가해야하고,
만약에 template 필드를 추가하지 않으려면 DB에 저장을 못하는 것 같아서
고민하다가 잠시 잊고 올려버렸습니다..
> [feat] 프로젝트 파일 생성 및 목록 불러오기 API 작성

- backend/src/main/java/com/nakaligoba/backend/repository/ProjectRepository.java
> ProjectRepository 파일 내에 메소드명 오타 수정

- frontend/package.json
- frontend/src/pages/IDEPage/components/header/components/ProjectTitleButton.jsx
- frontend/src/pages/IDEPage/components/header/index.jsx
- frontend/src/pages/IDEPage/components/modal/index.jsx
- frontend/src/pages/IDEPage/index.jsx
> [Feat] 모달 컴포넌트 설정 및 추가

- backend/src/main/resources/api/project/create.yaml
- backend/src/main/resources/api/project/save.yaml
- backend/src/main/resources/api/root.yaml
- docs/output.yaml
> Swagger UI 최신화

- backend/src/main/resources/db/schema.sql
- files 테이블에 create_at, updated_at 추가
> [docs] files 테이블 생성일 수정일 추가

- backend/src/main/java/com/nakaligoba/backend/BackendApplication.java
- backend/src/main/java/com/nakaligoba/backend/controller/FileController.java
- backend/src/main/java/com/nakaligoba/backend/entity/FileEntity.java
- backend/src/main/java/com/nakaligoba/backend/entity/ProjectEntity.java
- backend/src/main/java/com/nakaligoba/backend/service/FileService.java
- backend/src/main/java/com/nakaligoba/backend/service/ProjectService.java
작업파일 내에 있는 스키마를 참고하여 DB에 저장해야되는 부분들을 수정하고 저장하였습니다.
createdAt 또는 updatedAt 컬럼이 정상적으로 작동하기 위해서 
BackendApplication 클래스에 @EnableJpaAuditing 추가하면 해결될 것같아서 추가했습니다!
+
수정이 더 필요한 곳이 있다면 더 보완하도록 하겠습니다!
> [fix] 메타데이터 추가 및 BackendApplication.java파일에 @EnableJpaAuditing 추가

- backend/src/main/java/com/nakaligoba/backend/BackendApplication.java
- backend/src/main/java/com/nakaligoba/backend/config/JpaConfig.java
- backend/src/main/java/com/nakaligoba/backend/entity/MemberEntity.java
- backend/src/main/java/com/nakaligoba/backend/service/MemberService.java
- backend/src/main/resources/application-test.yaml
- backend/src/test/java/com/nakaligoba/backend/config/JpaConfigTest.java
- `JpaConfig`에 `JpaAuditing` 적용
- `MemberEntity`에 `@Setter` 제거
- `MemberEntity` `setter`관련 코드 수정
> [fix] createat updatedat 값 자동 주입

- frontend/package.json
- frontend/src/pages/IDEPage/components/file_explorer/TabSettings.jsx
- frontend/src/pages/IDEPage/components/file_explorer/index.jsx
- frontend/src/pages/IDEPage/components/modal/index.jsx
- frontend/src/service/apiUtils.js
- frontend/src/service/projectService.js
> 96 re idepage project create modal UI 구현

- backend/src/main/java/com/nakaligoba/backend/controller/ProjectController.java
- backend/src/main/java/com/nakaligoba/backend/service/ProjectService.java
- 프로젝트 목록 읽기 API에 id 추가
Closes #106
> 프로젝트 목록 읽기 api 수정

- backend/src/main/java/com/nakaligoba/backend/controller/ProjectController.java
- backend/src/main/java/com/nakaligoba/backend/entity/ProjectEntity.java
- backend/src/main/java/com/nakaligoba/backend/repository/MemberProjectRepository.java
- backend/src/main/java/com/nakaligoba/backend/repository/ProjectRepository.java
- backend/src/main/java/com/nakaligoba/backend/service/ProjectService.java
프로젝트 파일을 삭제할 때, cascadeType.REMOVE를 하여 삭제할때만 연관된 다른 엔티티에도 삭제되도록 하였습니다.
프로젝트 파일의 name, decription을 수정하고 ProjectRepository에 저장하였습니다.
> [feat] 프로젝트 파일 수정 및 삭제 기능추가

- backend/build.gradle
- backend/src/main/java/com/nakaligoba/backend/config/WebSocketConfig.java
- backend/src/main/java/com/nakaligoba/backend/controller/ChatController.java
- backend/src/main/java/com/nakaligoba/backend/entity/ChatMessage.java
- backend/src/main/java/com/nakaligoba/backend/repository/ChatMessageRepository.java
- backend/src/main/java/com/nakaligoba/backend/service/ChatMessageService.java
일단 필요한 필드들을 하드 코드에서 구현시켰습니다. 
일단 최소 기능 우선적으로 구현했고, 프론트 UI에 맞춰보도록 하겠습니다.
Closes #20
> feat: 채팅 구현

- backend/src/main/java/com/nakaligoba/backend/handler/WebSocketHandler.java
> add: 웹소켓 핸들러

- frontend/src/pages/IDEPage/components/chatroom/component/Message.jsx
- frontend/src/pages/IDEPage/components/chatroom/index.jsx
> feat: 채팅 통합

- frontend/src/pages/IDEPage/components/chatroom/index.jsx
> fix: 웹브라우저 새로고침 혹은 닫는 경우 세션 관련 에러

- frontend/src/pages/IDEPage/components/console/index.jsx
- frontend/src/pages/IDEPage/components/editor/index.css
- frontend/src/pages/IDEPage/components/editor/index.jsx
- frontend/src/pages/IDEPage/components/sidebar/index.jsx
- frontend/src/pages/IDEPage/index.jsx
Sidebar 에 Console 토글 버튼 추가
Sidebar 버튼 클릭 시 Editor와 Console 크기 변화
>  Console 토글 버튼 추가 및 idepage UI 수정

- backend/src/main/java/com/nakaligoba/backend/controller/FileController.java
- backend/src/main/java/com/nakaligoba/backend/service/FileService.java
> [feat] 파일 삭제 API 추가

- backend/src/main/java/com/nakaligoba/backend/config/SecurityConfig.java
- backend/src/main/java/com/nakaligoba/backend/controller/FileController.java
- backend/src/main/java/com/nakaligoba/backend/controller/ProjectController.java
- backend/src/main/java/com/nakaligoba/backend/filter/CorsFilter.java
- backend/src/main/java/com/nakaligoba/backend/service/ReadProjectService.java
- backend/src/main/resources/api/file/file.yaml
> 프로젝트 디렉터리구조 읽기

- frontend/src/pages/IDEPage/components/chatroom/index.jsx
- frontend/src/pages/IDEPage/index.jsx
> 로그인시 전달되는 유저이름을 chat 컴포넌트 디스플레이 이름으로 전달

- frontend/src/pages/IDEPage/components/header/components/Button.jsx
- frontend/src/pages/IDEPage/components/header/index.jsx
- frontend/src/pages/IDEPage/components/invite/index.jsx
- frontend/src/pages/IDEPage/index.jsx
> design: invite 탭 UI 작성

- backend/src/main/java/com/nakaligoba/backend/controller/FileController.java
- backend/src/main/java/com/nakaligoba/backend/controller/ProjectController.java
기존의 test@test.com 을 getEmailFromSpringSession()로 가져온 이메일로 수정하였습니다.
> [fix] jwtUtils에서 이메일 추출하여 변경

- frontend/src/pages/IDEPage/components/file_explorer/index.jsx
- frontend/src/pages/IDEPage/components/modal/index.jsx
- frontend/src/pages/IDEPage/components/sidebar/index.jsx
- frontend/src/pages/IDEPage/index.jsx
- frontend/src/service/FileService.js
- frontend/src/service/apiUtils.js
- frontend/src/service/projectService.js
프로젝트 기본 디렉토리 구조 수정
프로젝트 수정 기능 api 수정
프로젝트클릭시 디렉토리 구조 반영  
현재는 test5 프로젝트에만 기본 디렉토리가 있습니다 
> 프로젝트 수정 기능 content 추가

- frontend/src/pages/IDEPage/components/file_explorer/index.jsx
- frontend/src/pages/IDEPage/components/modal/index.jsx
- frontend/src/pages/IDEPage/components/sidebar/index.jsx
- frontend/src/pages/IDEPage/index.jsx
- frontend/src/service/FileService.js
projects 에서 selectedproject 일부 관리 
> projects 배열에서 selectedProject 상태관리

- frontend/src/pages/IDEPage/components/file_explorer/TabSettings.jsx
- frontend/src/pages/IDEPage/components/file_explorer/index.jsx
- frontend/src/pages/IDEPage/components/modal/index.jsx
- frontend/src/pages/IDEPage/components/sidebar/index.jsx
- frontend/src/pages/IDEPage/index.jsx
- frontend/src/service/FileService.js
> 파일 생성 api 구현

- frontend/src/pages/IDEPage/components/file_explorer/index.jsx
- frontend/src/pages/IDEPage/components/modal/index.jsx
- frontend/src/pages/IDEPage/components/sidebar/index.jsx
파일 생성을 위한 selectedProject props 복구 
> file_explorer props selectedProject 복구

- frontend/src/pages/IDEPage/components/chatroom/index.jsx
- frontend/src/pages/IDEPage/index.jsx
selectedProject의 me 필드를 파싱해서 chat 컴포넌트로 전달해서 display name으로 설정하게 했습니다.
> feat: 유저 이름을 상태로 받아와서 chat 표시 이름으로 설정

- frontend/src/pages/IDEPage/components/editor/index.jsx
- frontend/src/pages/IDEPage/components/file_explorer/index.jsx
- frontend/src/pages/IDEPage/components/sidebar/index.jsx
- frontend/src/pages/IDEPage/index.jsx
IDEPage에 `selectedProejct`, `selectedFiledId`를 두어 props로 `Editor`까지 내려주었습니다.
`useEffect`로 상태가 변경되면 `Editor`에서 파일 읽기 요청을 한 후 `activeTab`을 `selectedFileId`에 해당하는 파일 명으로 바꾸고 `tab`에 해당 파일의 title과 content를 추가했습니다.
> feat: 파일 읽기 API 연결
